function getUID(){var c=function(){return(1+Math.random())*4096|0};return c()+c()+c()+c()+c()+c()}
jQuery.fn.wptabs=function(c){var b,a=jQuery.extend({},jQuery.fn.wptabs.defaults,c);this.each(function(){uid=getUID();var d=jQuery(this);d.prepend('<ul class="ui-tabs-nav" />');var g=d.children(a.h3Class).wrap('<div class="ui-tabs-panel"></div>');d.find("div.ui-tabs-panel:last-child").after('<p id="jqtemp">');g.each(function(){jQuery(this).parent().append(jQuery(this).parent().nextUntil("div.ui-tabs-panel"))});d.find(".ui-tabs-panel").children(a.h3Class).each(function(){if(jQuery(this).children(a.linkAjaxClass).length!=
0){b=' href="'+jQuery(this).children(a.linkAjaxClass).attr("href")+'" title="'+jQuery(this).text()+'"';e=jQuery(this).text().replace(/\s/gm,"_")}else{var e=jQuery(this).text().replace(/\s/gm,"_")+"_"+uid++;b=' href="#'+e+'"'}jQuery(this).parent().parent().children("ul.ui-tabs-nav").append("<li><a "+b+">"+jQuery(this).text()+"</a></li>");jQuery(this).parent().attr("id",e);panelWidth=jQuery(this).width()-20;jQuery(this).find("img").css({width:panelWidth});jQuery(this).find("iframe").css({width:"600px"})}).hide();
if(d.find("div.ui-tabs").length==0){d.find("ul").before("<div class='ui-tabs'>");d.find(".ui-tabs").each(function(){jQuery(this).append(jQuery(this).nextUntil("p#jqtemp"))})}tabsobj={};if(a.effect=="slideDown")tabsobj.effect={height:"toggle",speed:a.effectSpeed};else if(a.effect=="fadeIn")tabsobj.effect={opacity:"toggle",speed:a.effectSpeed};if(a.cookie)tabsobj.cookie={expires:30};var f=d.children(".ui-tabs").tabs(tabsobj);jQuery("ul.ui-tabs-nav").each(function(){jQuery("li:first",this).addClass("first-li");
jQuery("li:last",this).addClass("last-li")});a.alwaysRotate!="disable"&&jQuery(this+"[class*=tab-rotate]").each(function(){rotateSpeed=jQuery(this).attr("class").match(/tab-rotate-(.*)/,"$1");if(rotateSpeed!=null){if(rotateSpeed[1].match(/(\d){1,2}s/,"$1"))rotateSpeed[1]=rotateSpeed[1].replace(/s$/,"")*1E3;rotateSpeed=rotateSpeed[1];alwaysRotate=a.alwaysRotate=="always"?true:false}jQuery(this).children(".ui-tabs").tabs("rotate",rotateSpeed,alwaysRotate)});if(a.topNav||a.bottomNav){d.find("div.ui-tabs-panel").each(function(e){!a.topNav||
jQuery(this).prepend('<div class="tab-top-nav" />');!a.bottomNav||jQuery(this).append('<div class="tab-bottom-nav" />');var h=jQuery(this).parent().children(".ui-tabs-panel").length-1;if(e!=0){!a.topNav||jQuery(this).children(".tab-top-nav").prepend('<a href="#" class="backward prev-tab">'+a.tabPrevText+"</a>");!a.bottomNav||jQuery(this).children(".tab-bottom-nav").append('<a href="#" class="backward prev-tab">'+a.tabPrevText+"</a>")}if(e!=h){!a.topNav||jQuery(this).children(".tab-top-nav").append('<a href="#" class="forward next-tab">'+
a.tabNextText+"</a>");!a.bottomNav||jQuery(this).children(".tab-bottom-nav").append('<a href="#" class="forward next-tab">'+a.tabNextText+"</a>")}});jQuery("a.forward, a.backward").click(function(){var e=d.find(".ui-tabs").tabs("option","selected");e=jQuery(this).hasClass("backward")?e-1:e+1;f.tabs("select",e);return false})}f.tabs("option","disabled",false);if(a.position=="bottom"||jQuery(this).hasClass("tabs-bottom")){jQuery("ul.ui-tabs-nav",this).each(function(){jQuery(this).appendTo(jQuery(this).parent()).addClass("ul-bottom")});
d.children(".ui-tabs").addClass("bottom-tabs").children(".ui-tabs-panel").each(function(){jQuery(this).addClass("bottom-tabs")})}typeof WPUIOpts!="undefined"&&d.append('<a class="thickbox cap-icon-link" title="" href="http://kav.in"><img src="'+wpUIOpts.pluginUrl+'/images/cquest.png" alt="Cap" /></a>')});return this};
jQuery.fn.wptabs.defaults={h3Class:"h3.wp-tab-title",linkAjaxClass:"a.wp-tab-load",topNav:typeof wpUIOpts!="undefined"&&wpUIOpts.topNav=="on"?true:false,bottomNav:typeof wpUIOpts!="undefined"&&wpUIOpts.bottomNav=="on"?true:false,position:"top",navStyle:typeof wpUIOpts!="undefined"?wpUIOpts.tabsLinkClass:"",effect:typeof wpUIOpts!="undefined"?wpUIOpts.tabsEffect:"",effectSpeed:typeof wpUIOpts!="undefined"?wpUIOpts.effectSpeed:"",alwaysRotate:typeof wpUIOpts!="undefined"?wpUIOpts.alwaysRotate:"",tabPrevText:typeof wpUIOpts!=
"undefined"&&wpUIOpts.tabPrevText!=""?wpUIOpts.tabPrevText:"&laquo; Previous",tabNextText:typeof wpUIOpts!="undefined"&&wpUIOpts.tabNextText!=""?wpUIOpts.tabNextText:"Next &raquo;",cookie:true};
jQuery.fn.wpaccord=function(c){var b,a,d,g=jQuery.extend({},jQuery.fn.wpaccord.defaults,c);this.each(function(){var f=jQuery(this);f.append('<p id="jqtemp" />');f.find("p, br").filter(function(){return jQuery.trim(jQuery(this).text())===""}).remove();b=f.find("h3:first").wrap('<div class="accordion">');b.each(function(){jQuery(this).parent().append(jQuery(this).parent().nextUntil("p#jqtemp"))});f.find(g.h3Class).each(function(){a=jQuery(this).children(g.linkAjaxClass);if(a.length!=0){d=a.attr("href");
a.parent().after("<div></div>");jQuery(this).next().load(wpUIOpts.wpUrl+"/"+d);jQuery(this).text(jQuery(this).children().text())}});jQuery(".accordion").accordion({autoHeight:false});jQuery(".accordion h3.ui-accordion-header:last").addClass("last-child");f.find("p#jqtemp").remove()})};jQuery.fn.wpaccord.defaults={h3Class:"h3.wp-tab-title",linkAjaxClass:"a.wp-tab-load",effect:typeof wpUIOpts!="undefined"?wpUIOpts.accordEffect:""};
jQuery.fn.wpspoiler=function(c){var b,a;b=jQuery.extend({},jQuery.fn.wpspoiler.defaults,c);return this.each(function(){var d=jQuery(this);d.addClass("ui-collapsible");d.children(b.headerClass).each(function(){jQuery(this).append('<span class="'+b.spanClass.replace(/\./,"")+'" style="float:right"></span>').find(b.spanClass).css({fontSize:"0.786em"});jQuery(this).click(function(){jQuery(this).delay(2E3).toggleClass("ui-state-active");b.fade=jQuery(this).hasClass("fade-false")?false:true;b.slide=jQuery(this).hasClass("slide-false")?
false:true;aniOpts={};if(b.fade)aniOpts.opacity="toggle";if(b.slide)aniOpts.height="toggle";if(b.slide||b.fade){if(jQuery(this+"[class*=speed-]").length)speed=(animSpeed=jQuery(this).attr("class").match(/speed-(.*)\s|\"/,"$1"))?animSpeed[1]:b.speed;jQuery(this).next("div.ui-collapsible-content").animate(aniOpts,b.speed)}else jQuery(this).next("div.ui-collapsible-content").toggle(b.speed);a=jQuery(this).children(b.spanClass).text();jQuery(this).find(b.spanClass).text(a==b.showText?b.hideText:b.showText)}).next().hide().prev().find(b.spanClass).text(b.showText)})})};
jQuery.fn.wpspoiler.defaults={hideText:typeof wpUIOpts!="undefined"?wpUIOpts.spoilerHideText:"",showText:typeof wpUIOpts!="undefined"?wpUIOpts.spoilerShowText:"",fade:true,slide:true,speed:600,spanClass:".toggle_text",headerClass:"h3.ui-collapsible-header"};
jQuery.fn.extend({tooltips:function(c){c=$.extend({background:"#000",gradient:"",bordercolor:"#888",textcolor:"#EEE",shadow:"0 1px 3px #000",effect:"fade",forceUse:false,disableOn:""},c);return this.each(function(){var b=c,a=jQuery(this);attrName=a.is("img")?"alt":"title";a.not(b.disableOn).mouseover(function(){getAttr=a.attr(attrName);if(getAttr.length==0)if(b.useValue==true)getAttr=a.text();else return;a.append('<div id="toolztip"><div class="tooltip-arrow-up"></div>'+getAttr+'<div class="tooltip-arrow-down"></div></div>');
jQuery("#toolztip").css({backgroundImage:b.background,borderColor:b.bordercolor,color:b.textcolor}).attr("style","box-shadow: "+b.shadow+"; -moz-border-shadow:"+b.shadow+";").attr("style","background-image: "+b.gradient+"; background-image:"+b.gradient+";");jQuery("#toolztip div.tooltip-arrow-down").hide();if(b.effect=="slide")jQuery("#tooltip").slideDown("500");else b.tipEffect=="fade"&&jQuery("#tooltip").fadeIn(500)}).mousemove(function(){}).mouseleave(function(){a.find("#toolztip").remove()})})}});
jQuery.cookie=function(c,b,a){if(arguments.length>1&&(b===null||typeof b!=="object")){a=jQuery.extend({},a);if(b===null)a.expires=-1;if(typeof a.expires==="number"){var d=a.expires,g=a.expires=new Date;g.setDate(g.getDate()+d)}return document.cookie=[encodeURIComponent(c),"=",a.raw?String(b):encodeURIComponent(String(b)),a.expires?"; expires="+a.expires.toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.secure?"; secure":""].join("")}a=b||{};g=a.raw?function(f){return f}:
decodeURIComponent;return(d=RegExp("(?:^|; )"+encodeURIComponent(c)+"=([^;]*)").exec(document.cookie))?g(d[1]):null};
jQuery.fn.wpuipre=function(){var c=jQuery(this);c.each(function(){preW=jQuery(this).width();jQuery(this).css({overflow:"hidden !important"});jQuery(this).wrapInner('<span class="code-wrapper" />');c.hover(function(){var b=jQuery("span.code-wrapper",this).width()+10;b>580&&jQuery(this).stop(true,false).css({zIndex:"100",position:"relative"}).animate({width:b+"px"})},function(){jQuery(this).stop(true,false).animate({width:preW})})});return c};
